FileFolder/config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  get 'welcome/index'

  resources :docs

  authenticated :user do
    root "docs#index", as: "authenticated_root"
  end

  root 'welcome#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

FileFolder/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

FileFolder/app/models/doc.rb
class Doc < ApplicationRecord
  belongs_to :user
end

FileFolder/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :docs
end

FileFolder/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

FileFolder/app/controllers/docs_controller.rb
class DocsController < ApplicationController
  before_action :find_doc, only: [:show, :edit, :update, :destroy]

  def index
    @docs = Doc.where(user_id: current_user).all.order("created_at DESC")
  end

  def show
  end

  def new
    @doc = current_user.docs.build
  end

  def create
    @doc = current_user.docs.build(doc_params)

    if @doc.save
      redirect_to @doc
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @doc.update(doc_params)
      redirect_to @doc
    else
      render 'edit'
    end
  end

  def destroy
    @doc.destroy
    redirect_to docs_path
  end

  private

    def find_doc
      @doc = Doc.find(params[:id])
    end

    def doc_params
      params.require(:doc).permit(:title, :content)
    end
end

FileFolder/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

FileFolder/app/helpers/application_helper.rb
module ApplicationHelper
end

FileFolder/app/helpers/docs_helper.rb
module DocsHelper
end

FileFolder/app/helpers/welcome_helper.rb
module WelcomeHelper
end

FileFolder/app/views/docs/_form.html.haml
= simple_form_for @doc do |f|
  = f.input :title
  = f.input :content
  = f.button :submit, class: "button"

FileFolder/app/views/docs/edit.html.haml
.wrapper_with_padding
  %h1 Edit file

  = render 'form'

  = link_to "Cancel", doc_path, class: "button"

FileFolder/app/views/docs/index.html.haml
.wrapper_with_padding
  #docs.clearfix
    - if @doc.blank?
      - @docs.each do |doc|
        %a{href: (url_for [doc])}
          .doc
            %p.title= doc.title
            %p.date= "Created " + time_ago_in_words(doc.created_at) + " ago"
            %p.content= truncate(doc.content, length:50)
    - else
      %h2 Create File!
      %p Uplode your first file here
      = link_to "New File", new_doc_path

.wrapper_with_padding
  %div{style: "text-align: center; margin-left: auto; margin-right: auto"}
    %a= link_to "New File", new_doc_path, class: "button", style: "border-radius:1.2rem;"

FileFolder/app/views/docs/new.html.haml
.wrapper_with_padding
  %h1 New File

  = render 'form'

FileFolder/app/views/docs/show.html.haml
.wrapper_with_padding
  #doc_show
    %h1.title= @doc.title
    %p= simple_format(@doc.content)

    .buttons
    = link_to "All Files", docs_path, class: "filebutton"
    = link_to "Edit", edit_doc_path(@doc), class: "filebutton"
    = link_to "Delete", doc_path(@doc), method: :delete, data: { confirm: "Are you sure to delete this file?"}, class: "filebutton"

FileFolder/app/views/layouts/application.html.haml
!!!
%html
%head
  %title FileFolder | Your File Garage
  = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true
  = javascript_include_tag 'application', 'data-turbolinks-track' => true
  = csrf_meta_tags

%body
  %header
    .header_inner
      = link_to "FileFolder", root_path, id:"logo"

      %nav
        - if user_signed_in?
          = link_to "New Doc", new_doc_path
          = link_to "Sign Out", destroy_user_session_path, method: :delete

        - else
          = link_to "Login", new_user_session_path
  .wrapper_with_padding
    %p.notice{style: "color: purple"}= notice
    %p.alert= alert

  %wrapper
    .white_place_holder
    %br

  = yield

  %footer
    %p Creted by Tempay @2017

FileFolder/app/views/welcome/index.html.haml
#banner
  .banner_content
    %h1 FileFolder
    %p Don't get messed up, get a Folder for your Files!
    = link_to "Get Started", new_user_registration_path, :class => "button"

#div
  .white_place_holder

#callouts
  .callout_inner
    .wrapper
      .callout
        .white_place_holder
        %h2 John Dow
        %p The names "John Doe" or "John Roe" for men, "Jane Doe" or "Jane Roe" for women, "Johnny Doe" and "Janie Doe" for children, or just "Doe" non-gender-specifically are used as placeholder names for a party whose true identity is unknown or must be withheld in a legal action, case, or discussion.[1] The names are also used to refer to a corpse or hospital patient whose identity is unknown. This practice is widely used in the United States and Canada, but is always used in other English-speaking countries including the United Kingdom, from which the use of "John Doe" in a legal context originates. The names "Joe Bloggs" or "John Smith" are used in the UK as placeholder names, (mainly to mean 'any old person', the classic 'Everyman')[citation needed] as well as in Australia and New Zealand.
        %br
        %p John Doe is sometimes used to refer to a typical male in other contexts as well, in a similar manner to John Q. Public in the United States or Joe Public, John Smith or Joe Bloggs in Britain. For example: the first name listed on a form might be John Doe, along with a fictional address or other fictional information to provide an example of how to fill in the form. The name is also used frequently in US popular culture, for example in the Frank Capra film Meet John Doe. John Doe was also the name of a 2002 American television series.
        .white_place_holder

#bottom_cta
  .wrapper
    %h2 Start Folding!
    %br
    %br
    =link_to "Get Started", new_user_registration_path, :class => "button"